---
services:
  gotinystatus:
    build:
      context: .
    working_dir: /usr/src/myapp
    env_file: .env
    volumes:
      - .:/usr/src/myapp
    restart: unless-stopped
    ports:
      - 3030:3030

